### ISSUE TITLE
Consensus.cpp::checkRepetitive :Is there a bug here?

### ISSUE THREAD

**Issue by lhclqslove** [qm2/NanoSpring#5]
bool Consensus::checkRepetitive(read_t readID){
    std::string readStr;   
    rD->getRead(readID, readStr);
    //check the hamming distance with different offsets
    //I choose 6 here; it is tunable
    size_t readLen = readStr.length();
    for (size_t i = 1; i <= 6; i++){
        size_t countSameBase = 0;
        for(size_t j = 0; j < readLen; j++){
            //check how many same bases the two string share
            if(readStr[j] != readStr[(j+i)%readLen])//Why not here ==???
                countSameBase++;
        }
        //the ratio 0.9 is tunable
        if(countSameBase > 0.9 * (double)readLen)
            return true;
    }   
    return false;

}
I am confused here if(readStr[j] != readStr[(j+i)%readLen])

**Comment by qm2** [comment]
Thank you so much for pointing this out! It does seem like a mistake in the code. We will look into a fix and test it on a few datasets. Thanks again!

**Comment by lhclqslove** [comment]
I should be thankful because I learned a lot from the source code.Thank you for your reply

**Comment by qm2** [comment]
We fixed the bug in the function **checkRepetitive** and tested the new parameter on a few different datasets. Thank you so much again for pointing it out! Feel free to let us know if you find any other issues.

**Comment by shubhamchandak94** [comment]
Just to add on why the old buggy code still gave the intended results: Let’s say you have ATATATATATATATATA… (which along with it's reverse complement was the most common repeating pattern we observed). Then for a shift of one, the count of (s[i]!=s[i+1]) is close to 1. Whereas for a random string you would expect the count of (s[i]!=s[i+1]) to be close to 0.75. So the old check was also able to filter out repetitive sequences to some extent.
